version: "3.8"

services:
  gateway-api:
    container_name: gateway-api
    build: ./gateway-api
    ports:
      - "8080:8080"
    volumes:
      - ./gateway-api/microservices:/app/microservices
    networks:
      - mvp-net

  web-ui:
    container_name: web-ui
    build: ./web-ui
    ports:
      - "5173:5173"
    depends_on:
      - gateway-api
    networks:
      - mvp-net

networks:
  mvp-net:
    external: true
