version: "3.8"

services:
  db:
    container_name: roble-db
    image: postgres:15
    environment:
      POSTGRES_DB: colegio
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  api:
    container_name: roble-api
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: roble-db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: colegio
    networks:
      - mvp-net

volumes:
  db_data:

networks:
  mvp-net:
    external: true
